const locationNames: Record<string, string> = {
    ash: 'Ashburn, USA',
    hil: 'Hillsboro, USA',
    fsn1: 'Falkenstein, Germany',
    nbg1: 'Nuremberg, Germany',
    hel1: 'Helsinki, Finland',
    sin: 'Singapore',
    nyc1: 'New York 1, USA',
    nyc2: 'New York 2, USA',
    nyc3: 'New York 3, USA',
    sfo1: 'San Francisco 1, USA',
    sfo2: 'San Francisco 2, USA',
    sfo3: 'San Francisco 3, USA',
    ams2: 'Amsterdam 2, Netherlands',
    ams3: 'Amsterdam 3, Netherlands',
    sgp1: 'Singapore',
    lon1: 'London, UK',
    fra1: 'Frankfurt, Germany',
    tor1: 'Toronto, Canada',
    blr1: 'Bangalore, India',
    syd1: 'Sydney, Australia',
    atl1: 'Atlanta, USA',
    'us-central1': 'Iowa, USA',
    'us-east1': 'South Carolina, USA',
    'us-west1': 'Oregon, USA',
    'europe-west1': 'Belgium',
    'europe-west4': 'Netherlands',
    'asia-southeast1': 'Singapore',
    'asia-northeast1': 'Tokyo, Japan',
    'australia-southeast1': 'Sydney, Australia',
    'southamerica-east1': 'São Paulo, Brazil'
}

export default locationNames